apiVersion: apps/v1
kind: Deployment
metadata:
    name: k8s-deployment
spec:
    template:
        metadata:
            name: k8s
            labels:
                app: k8s
                tier: backend
        spec:
            containers:
            - name: k8s-container
              image: xxxxxxxxxxxx
              ports:
              - containerPort: 8888
    replicas: 2
    selector:
        matchLabels:
            app: k8s
            tier: backend
---
apiVersion: v1
kind: Service
metadata:
    name: k8s-service-backend
spec:
    type: LoadBalancer
    ports:
        - targetPort: 8888
          port: 8888
    selector:
        app: k8s
        tier: backend