apiVersion: apps/v1
kind: Deployment
metadata:
    name: kube-log-deployment
spec:
    template:
        metadata:
            name: kube-log
            labels:
                app: kube-log
                tier: backend
        spec:
            containers:
            - name: kube-log-container
              image: psmsenthilkumar/kube-log
              args: ["-file", "/var/log/logging-app/logging-app.log"]
              volumeMounts:
              - name: logging-app-log-dir
                mountPath: /var/log/logging-app
            volumes:
            - name: logging-app-log-dir
              hostPath:
                path: /var/log/containers
              ports:
              - containerPort: 5051
    replicas: 2
    selector:
        matchLabels:
            app: kube-log
            tier: backend
            
---         
   
apiVersion: v1
kind: Service
metadata:
    name: kube-log-service-backend
spec:
    type: LoadBalancer
    ports:
        - targetPort: 5051
          port: 5051
    selector:
        app: kube-log
        tier: backend
            
